const IDLE_STATE = 'IDLE_STATE';
const JUMP_STATE = 'JUMP_STATE';
const ATTACK_STATE = 'ATTACK_STATE';
const JUMP_ATTACK_STATE = 'JUMP_ATTACK_STATE';
const CROUCH_STATE = 'CROUCH_STATE';
const COMBO_STATE = 'COMBO_STATE';

export default {
  IDLE_STATE,
  JUMP_STATE,
  ATTACK_STATE,
  JUMP_ATTACK_STATE,
  CROUCH_STATE,
  COMBO_STATE
};
